version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    # Look for go.mod file in the root directory
    directory: "/"
    # Check for updates every week
    schedule:
      interval: "weekly"
